//<editor-fold defaultstate="collapsed" desc="Jibberish">
package gui;

import components.Language;
import components.Test;
import components.enums.TestSpeed;
import components.enums.TestType;
import connections.DatabaseMySQL;
import java.util.ArrayList;
import java.util.List;
//</editor-fold>

/**
 * In this class you can find all properties and operations for the Test Frame.
 *
 * @organization: Moridrin
 * @author J.B.A.J. Berkvens
 * @date 2014/04/14
 */
public class DatabaseSelector extends javax.swing.JFrame {

    //<editor-fold defaultstate="collapsed" desc="Declarations">
    private final MainFrame mainFrame;
    private Language language;
    //</editor-fold>

    //<editor-fold desc="Operations">
    //<editor-fold defaultstate="collapsed" desc="Constructor(language, testSpeed, testType)">
    /**
     * Creates new form TestFrame and starts the first question.
     *
     * @param mainFrame
     * @param language
     */
    public DatabaseSelector(MainFrame mainFrame, Language language) {
        this.mainFrame = mainFrame;
        this.language = language;
        initComponents();
        jTextFieldNewDatabaseName.setVisible(false);
        if (language == null) {
            jComboBoxDatabase.removeAllItems();
        }
        loadDatabases();
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Generated Code">
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSelect = new javax.swing.JButton();
        jComboBoxDatabase = new javax.swing.JComboBox();
        jLabelSelect = new javax.swing.JLabel();
        jTextFieldNewDatabaseName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonSelect.setText("Select");
        jButtonSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectActionPerformed(evt);
            }
        });

        jComboBoxDatabase.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "New" }));

        jLabelSelect.setText("Select");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSelect)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxDatabase, 0, 229, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNewDatabaseName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSelect)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSelect)
                    .addComponent(jLabelSelect)
                    .addComponent(jTextFieldNewDatabaseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="loadDatabases()">
    public void loadDatabases() {
        List<String> databases = new ArrayList<>();
        DatabaseMySQL.loadDatabases(databases);
        for (String database : databases) {
            jComboBoxDatabase.addItem(database);
        }
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Button Select">
    private void jButtonSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectActionPerformed
        if (language == null) {
            loading();
        } else {
            saving();
        }
    }//GEN-LAST:event_jButtonSelectActionPerformed
   //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="loading()">
    public void loading() {
        String languageName = jComboBoxDatabase.getSelectedItem().toString();
        language = new Language(languageName);
        DatabaseMySQL.load(language);
        mainFrame.setLanguage(language);
        this.dispose();
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="saving()">
    private void saving() {
        if (jComboBoxDatabase.isVisible()) {
            String languageName = jComboBoxDatabase.getSelectedItem().toString();
            if (languageName.equals("New")) {
                jComboBoxDatabase.setVisible(false);
                jTextFieldNewDatabaseName.setVisible(true);
            } else {
                DatabaseMySQL.save(language);
            }
        } else {
            String languageName = jTextFieldNewDatabaseName.getText();
            DatabaseMySQL.create(languageName);
            language.setName(languageName);
            DatabaseMySQL.save(language);
            this.dispose();
        }
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Generated Variable">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSelect;
    private javax.swing.JComboBox jComboBoxDatabase;
    private javax.swing.JLabel jLabelSelect;
    private javax.swing.JTextField jTextFieldNewDatabaseName;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
